ALTER TABLE risk ADD COLUMN IF NOT EXISTS ai_description TEXT;
ALTER TABLE risk ADD COLUMN IF NOT EXISTS ai_recommendations TEXT;
ALTER TABLE risk ADD COLUMN IF NOT EXISTS ai_processed BOOLEAN DEFAULT FALSE;