spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/risk_appetite_db
    username: postgres
    password: Prajwal@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}